DROP TABLE IF EXISTS migration_tr.tr_vitals;
CREATE TABLE migration_tr.tr_vitals (
Person_Id INT(11) NOT NULL ,
patient_id INT(11) DEFAULT NULL ,
Encounter_ID INT(11) DEFAULT NULL ,
Visit_reason varchar(255),
Systolic_pressure decimal(5,2) DEFAULT NULL,
Diastolic_pressure decimal(5,2) DEFAULT NULL,
Respiratory_rate decimal(5,2) DEFAULT NULL,
Pulse_rate decimal(5,2) DEFAULT NULL,
Oxygen_saturation decimal(5,2) DEFAULT NULL,
Weight decimal(5,2) DEFAULT NULL,
Height decimal(5,2) DEFAULT NULL,
Temperature decimal(5,2) DEFAULT NULL,
Muac decimal(5,2) DEFAULT NULL,
Last_menstrual_period date DEFAULT NULL,
Nurse_comments varchar(255),
Encounter_Date date NOT NULL,
encounter_provider INT(11),
date_created DATETIME NOT NULL,
location_id INT(11) DEFAULT NULL,
voided INT(11),
INDEX(patient_id),
INDEX(Person_Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
